"""Contract models for Native iOS Runtime v0.

Typed value records for the R2 public contract (sections 4-6): the v0 action
union, runtime status, observations with revision-bound elements, execution /
recovery results, and the machine-readable operation error with the
no-effect vs attempted-effect distinction.

These are deliberately permissive value records: bounds/enum/string/coordinate
validation belongs to the executor's whole-batch preflight (contract 4.3), so
invalid actions remain constructible here and a whole batch can be rejected
before the first device side effect.

Revisions are opaque plain ``str`` tokens generated by the runtime; callers
compare and pass them, nothing here parses them. Observation image bytes
remain in-process and are not part of these records. Public point/rect
coordinates are full-screen screenshot pixels of the observation revision
that produced them.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import ClassVar

__all__ = [
    "ATTEMPTED_EFFECT_CODES",
    "NO_EFFECT_CODES",
    "Action",
    "ActionOutcome",
    "Drag",
    "Element",
    "ErrorEffect",
    "ErrorCode",
    "ErrorPhase",
    "ExecutionResult",
    "FrameInfo",
    "Home",
    "LaunchApp",
    "LifecycleState",
    "ObserveRequest",
    "Observation",
    "Rect",
    "RecoveryResult",
    "RuntimeLimits",
    "RuntimeOperationError",
    "RuntimeStatus",
    "ScreenSize",
    "Swipe",
    "TapElement",
    "TapPoint",
    "TransportKind",
    "TypeText",
    "WdaState",
]


class LifecycleState(StrEnum):
    READY = "READY"
    DEGRADED = "DEGRADED"
    DISCONNECTED = "DISCONNECTED"
    CLOSED = "CLOSED"


class TransportKind(StrEnum):
    LOCKDOWN = "LOCKDOWN"
    RSD_USERSPACE = "RSD_USERSPACE"
    RSD_NATIVE = "RSD_NATIVE"
    RSD_TUNNELD = "RSD_TUNNELD"
    NONE = "NONE"


class WdaState(StrEnum):
    READY = "READY"
    UNAVAILABLE = "UNAVAILABLE"
    RECOVERING = "RECOVERING"
    NONE = "NONE"


class ErrorCode(StrEnum):
    # No-effect codes: raised before any device side effect (contract 5.1).
    INVALID_REQUEST = "INVALID_REQUEST"
    STALE_REVISION = "STALE_REVISION"
    NOT_READY = "NOT_READY"
    RUNTIME_CLOSED = "RUNTIME_CLOSED"
    UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION"
    OBSERVATION_FAILED = "OBSERVATION_FAILED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    # Attempted-effect codes: a device side effect was attempted (contract 5.2).
    ACTION_FAILED = "ACTION_FAILED"
    EFFECT_UNKNOWN = "EFFECT_UNKNOWN"


class ErrorPhase(StrEnum):
    PREFLIGHT = "preflight"
    LIFECYCLE = "lifecycle"
    EXECUTION = "execution"


class ErrorEffect(StrEnum):
    NONE = "NONE"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


NO_EFFECT_CODES: frozenset[ErrorCode] = frozenset({
    ErrorCode.INVALID_REQUEST,
    ErrorCode.STALE_REVISION,
    ErrorCode.NOT_READY,
    ErrorCode.RUNTIME_CLOSED,
    ErrorCode.UNSUPPORTED_ACTION,
    ErrorCode.OBSERVATION_FAILED,
    ErrorCode.RECOVERY_FAILED,
})

ATTEMPTED_EFFECT_CODES: frozenset[ErrorCode] = frozenset({
    ErrorCode.ACTION_FAILED,
    ErrorCode.EFFECT_UNKNOWN,
})


# --- v0 action union (contract 4.3) -----------------------------------------


@dataclass(frozen=True, kw_only=True)
class Action:
    """Base type of the v0 action union; ``kind`` names the action type."""

    kind: ClassVar[str]


@dataclass(frozen=True, kw_only=True)
class TapPoint(Action):
    """Tap at full-screen screenshot-pixel coordinates."""

    kind: ClassVar[str] = "tap_point"
    x: int
    y: int


@dataclass(frozen=True, kw_only=True)
class TapElement(Action):
    """Tap an element ref from the accepted observation revision only."""

    kind: ClassVar[str] = "tap_element"
    ref: str


@dataclass(frozen=True, kw_only=True)
class Drag(Action):
    """Press-drag-release between screenshot-pixel points; duration in seconds."""

    kind: ClassVar[str] = "drag"
    start_x: int
    start_y: int
    end_x: int
    end_y: int
    duration: float


@dataclass(frozen=True, kw_only=True)
class Swipe(Action):
    """Swipe in one of up/down/left/right by a normalized screen fraction (0, 1]."""

    kind: ClassVar[str] = "swipe"
    direction: str
    distance: float


@dataclass(frozen=True, kw_only=True)
class TypeText(Action):
    kind: ClassVar[str] = "type_text"
    text: str


@dataclass(frozen=True, kw_only=True)
class Home(Action):
    kind: ClassVar[str] = "home"


@dataclass(frozen=True, kw_only=True)
class LaunchApp(Action):
    """Launch by bundle id only; no human display-name resolution exists in v0."""

    kind: ClassVar[str] = "launch_app"
    bundle_id: str


# --- status (contract 4.1) ---------------------------------------------------


@dataclass(frozen=True, kw_only=True)
class RuntimeLimits:
    max_batch_actions: int


@dataclass(frozen=True, kw_only=True)
class RuntimeStatus:
    """Side-effect-free health/capability snapshot.

    Producers must keep ``capabilities`` free of device identifiers, pair
    records, screen text, and action payloads (contract 4.1).
    """

    contract_version: str
    lifecycle_state: LifecycleState
    transport: TransportKind
    wda_state: WdaState
    limits: RuntimeLimits
    current_revision: str | None = None
    capabilities: dict[str, object] = field(default_factory=dict)
    last_error_code: ErrorCode | None = None


# --- observation (contract 4.2) ----------------------------------------------


@dataclass(frozen=True, kw_only=True)
class ScreenSize:
    width: int
    height: int


@dataclass(frozen=True, kw_only=True)
class Rect:
    """Rectangle in full-screen screenshot pixels."""

    x: int
    y: int
    width: int
    height: int


@dataclass(frozen=True, kw_only=True)
class FrameInfo:
    """Captured-frame metadata; image bytes stay in-process, never here."""

    width: int
    height: int
    format: str


@dataclass(frozen=True, kw_only=True)
class Element:
    """One accessibility element of an observation.

    ``ref`` is opaque and valid only with the observation revision that
    created it. ``label``/``text``/``value`` carry accessibility content when
    the source supplies it; ``rect`` is in screenshot pixels when known.
    """

    ref: str
    role: str
    source: str
    label: str | None = None
    text: str | None = None
    value: str | None = None
    rect: Rect | None = None
    enabled: bool | None = None
    visible: bool | None = None


@dataclass(frozen=True, kw_only=True)
class Observation:
    """One immutable observation with its opaque revision token."""

    revision: str
    captured_at: datetime
    screen: ScreenSize
    frame: FrameInfo
    sources: tuple[str, ...]
    elements: tuple[Element, ...] = ()


@dataclass(frozen=True, kw_only=True)
class ObserveRequest:
    """Minimal observation request; default is the generic both-sources view."""

    sources: frozenset[str] = frozenset({"screenshot", "accessibility"})


# --- results (contract 4.3 / 4.5) --------------------------------------------


@dataclass(frozen=True, kw_only=True)
class ActionOutcome:
    """Per-action timing record for an executed batch (no action payloads)."""

    index: int
    kind: str
    duration_ms: float


@dataclass(frozen=True, kw_only=True)
class ExecutionResult:
    completed_actions: int
    accepted_revision_invalidated: bool
    outcomes: tuple[ActionOutcome, ...]


@dataclass(frozen=True, kw_only=True)
class RecoveryResult:
    """True when this call repaired plumbing (False when already healthy)."""

    repaired: bool


# --- machine-readable error (contract section 5) ------------------------------


class RuntimeOperationError(Exception):
    """Machine-readable runtime failure with effect semantics.

    Encodes the R2 section 5 distinction at construction time:

    - no-effect codes (contract 5.1) carry ``effect=NONE`` and a
      ``preflight``/``lifecycle`` phase, with no per-action counts;
    - attempted-effect codes ``ACTION_FAILED``/``EFFECT_UNKNOWN`` (contract
      5.2) require ``phase=execution``, ``effect=PARTIAL|UNKNOWN``,
      ``retry_safe=False``, ``revision_invalidated=True``, and the completed
      count plus failed action index. They must never be blindly replayed.

    Only structured fields are accepted, so the message can never leak
    payloads, screen text, or device identifiers.
    """

    def __init__(
        self,
        code: ErrorCode | str,
        phase: ErrorPhase | str,
        effect: ErrorEffect | str,
        *,
        retry_safe: bool,
        completed_actions: int | None = None,
        failed_action_index: int | None = None,
        revision_invalidated: bool = False,
    ) -> None:
        code = ErrorCode(code)
        phase = ErrorPhase(phase)
        effect = ErrorEffect(effect)
        if code in ATTEMPTED_EFFECT_CODES:
            if phase != ErrorPhase.EXECUTION:
                raise ValueError(
                    "attempted-effect error requires phase='execution'"
                )
            if effect not in (ErrorEffect.PARTIAL, ErrorEffect.UNKNOWN):
                raise ValueError(
                    "attempted-effect error requires effect PARTIAL or UNKNOWN"
                )
            if retry_safe is not False:
                raise ValueError(
                    "attempted-effect errors are never retry_safe"
                )
            if revision_invalidated is not True:
                raise ValueError(
                    "attempted-effect errors always invalidate the revision"
                )
            if completed_actions is None or failed_action_index is None:
                raise ValueError(
                    "attempted-effect errors require completed_actions"
                    " and failed_action_index"
                )
            if completed_actions < 0 or failed_action_index < 0:
                raise ValueError(
                    "completed_actions/failed_action_index must be non-negative"
                )
        else:
            if effect != ErrorEffect.NONE:
                raise ValueError(
                    f"no-effect error {code.value} requires effect='NONE'"
                )
            if phase == ErrorPhase.EXECUTION:
                raise ValueError(
                    f"no-effect error {code.value} cannot use phase='execution'"
                )
            if completed_actions is not None or failed_action_index is not None:
                raise ValueError(
                    "no-effect errors carry no per-action counts"
                )
        self.code = code
        self.phase = phase
        self.effect = effect
        self.retry_safe = retry_safe
        self.completed_actions = completed_actions
        self.failed_action_index = failed_action_index
        self.revision_invalidated = revision_invalidated
        summary = (
            f"{code.value}: phase={phase.value} effect={effect.value}"
            f" retry_safe={retry_safe}"
        )
        if completed_actions is not None:
            summary += (
                f" completed_actions={completed_actions}"
                f" failed_action_index={failed_action_index}"
            )
        if revision_invalidated:
            summary += " revision_invalidated=True"
        super().__init__(summary)
